"""
    Arbeitsagentur Bewerberbörse API

     Die Authentifizierung funktioniert über die clientId der Bewerberbörse:  **clientId:** jobboerse-bewerbersuche-ui  Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""

import unittest

from deutschland.Bewerberboerse.api.default_api import DefaultApi  # noqa: E501

from deutschland import Bewerberboerse


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bewerberboerse(self):
        """Test case for bewerberboerse

        Bewerberbörse  # noqa: E501
        """
        pass

    def test_bewerberdetails(self):
        """Test case for bewerberdetails"""
        pass


if __name__ == "__main__":
    unittest.main()
